In [1]:
import numpy as np

In [2]:
a=[1, 2, 3]
b=[4, 5, 6]
a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [3]:
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
a*b

array([ 4, 10, 18])

In [ ]:
# More Dimention

In [4]:
b=np.array([[1, 2, 3],[4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# Get Dimention 
b.ndim
b.shape
# Check type
b.dtype
# Check size
b=np.array([4, 5, 6], dtype='int16')
b.itemsize
#=>one number=two bytes
#total size
b.size*b.itemsize
b.nbytes


6

In [21]:
# accessing/change elements
b=np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print(b)
b[0, 0, -1]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


3

In [21]:
# accessing/change elements
b=np.array([[1, 2, 3],[4, 5, 6]])
b[0,0]=2
print(b)
b=np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print(b)
b[0,0,-1]

[[2 2 3]
 [4 5 6]]


In [23]:
a=np.ones((2, 2))
a

array([[1., 1.],
       [1., 1.]])

In [49]:
# Different type of array
a=np.zeros((2, 2))
print(a)
a=np.ones((2, 2))
print(a)
# Any other number
a=np.full((2, 2), 99, dtype='int16')
print(a)
b=np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
a=np.full_like(b, 99, dtype='int16')
#a=np.full(b.shape, 99, dtype='int16')
print(a)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[99 99]
 [99 99]]
[[[99 99 99]
  [99 99 99]]

 [[99 99 99]
  [99 99 99]]]


In [64]:
# random number
a=np.random.rand(1,3)
print(a)
np.random.random_sample(b.shape)

[[0.26610086 0.5873418  0.08240161]]


array([[[0.09253959, 0.33184244, 0.21881531],
        [0.9685415 , 0.6583261 , 0.71816864]],

       [[0.05981859, 0.29400106, 0.16164768],
        [0.42763482, 0.3900794 , 0.66327711]]])

In [69]:
# identity metrix
np.identity(5)*np.random.rand(5,1)

array([[0.48412691, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.1952959 , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.46040003, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.2448314 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.42804121]])

In [77]:
#repeat an array
a=np.array([[1, 2, 3]])
np.repeat(a, 3, axis=0)


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [103]:
# replace na 
a=np.array([[5, np.nan, 3]])
mask = np.isnan(a)
a[mask] =0
a

array([0, 1, 2])

In [132]:
# replace value base on condition
a = np.arange(10)
print(a)
a=np.where(a < 5, a, 10*a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 50 60 70 80 90]


In [12]:
np.empty([2, 2])
#np.empty([1, 2, 3], dtype=int)

array([[0.25, 0.25],
       [0.25, 0.25]])

# Copy array (this also happends to pandas):

In [78]:
a=np.array([[1, 2, 3]])
# point to the same object, not immutable (depending on the data type)
b=a 
b[0,0]=100
print(b)
print(a)

[[100   2   3]]
[[100   2   3]]


In [79]:
a=np.array([[1, 2, 3]])
print(a)
b=a.copy(deep=True)
#tuple immutible
b=a.copy()
b[0,0]=100
print(b)
print(a)

[[100   2   3]]
[[1 2 3]]


# Methematics

In [84]:
a=np.array([1, 2, 3])
a+2
a-2
a**2

array([1, 4, 9])

In [83]:
b=np.array([1, 0, 1])
a*b

array([1, 0, 3])

In [102]:
b=np.array([1, 1, 1])
a*b

array([[ 1., nan,  3.]])

# Linear Algebra

In [24]:
a=np.ones((2, 3))
print(a)
b=np.full((3, 2), 10)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[10 10]
 [10 10]
 [10 10]]


array([[30., 30.],
       [30., 30.]])

In [152]:
# find the determinate
c=np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

# Statistics

In [26]:
stats=np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
print('min value in the rows:', format(np.min(stats, axis=1)))
print('max value in the rows:', format(np.max(stats, axis=1)))
print('sum of the rows:', format(np.sum(stats, axis=1)))
print('sum value in each column:', format(np.sum(stats, axis=0)))

min value in the rows: [1 4]
max value in the rows: [3 6]
sum of the rows: [ 6 15]
sum value in each column: [5 7 9]


In [18]:
np.corrcoef(stats[:,0], stats[:,1])

array([[1., 1.],
       [1., 1.]])

In [6]:
np.histogram([1, 2, 1], bins=[0, 1, 2, 3])[0]

array([0, 2, 1])

In [8]:
np.histogram(np.arange(4), bins=np.arange(5), density=True)[0]

array([0.25, 0.25, 0.25, 0.25])

# Reshape

In [173]:
a=np.array([[1, 2, 3], [4, 5, 6]])
print(a)
b=a.reshape(3,2)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [175]:
# vertical stacking
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
np.vstack([a, b])

array([[1, 2, 3],
       [4, 5, 6]])

In [177]:
# horizontal stacking
np.hstack([a, b])

array([1, 2, 3, 4, 5, 6])

# Load data

In [47]:
example= np.genfromtxt("example.csv", delimiter=",", skip_header=1)
example=example.astype('int32')
example

array([[  174947.,   109454.],
       [  947483.,   905761.],
       [ 2012293.,  1989748.],
       [12890865.,  6707772.],
       [13009908.,  6826008.],
       [14666889.,  8490155.],
       [15392108.,  9209101.],
       [15395129.,  9217653.],
       [15400766.,  9222845.],
       [15407560.,  9228876.]])

In [67]:
example = np.genfromtxt("example.csv", dtype=None, delimiter=',', names=True)
print(example['user_id'])
example['user_id'].min()


[  174947   947483  2012293 12890865 13009908 14666889 15392108 15395129
 15400766 15407560]


174947

In [61]:
#np.array(example.dtype.names).tolist()
example.dtype.names

['user_id', 'dw_applicant_id']

# Boolen masking and advance indexing

In [134]:
example[:, 0]>13009908
np.any(example>13009908, axis=0)


array([ True, False])

In [135]:
np.all(example>13009908, axis=0)

array([False, False])

In [127]:
example[:, 0][example[:, 0]>13009908]

array([14666889, 15392108, 15395129, 15400766, 15407560], dtype=int32)

In [137]:
((example>1000)&(example<13009908))

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True]])

In [78]:
# indexing
a=np.array([1, 2, 3,4, 5, 6])
a[[1, 3, 5]]

array([2, 4, 6])

In [118]:
# replace missing using the first value
a=np.array([[5, np.nan,np.nan, 3]])
mask = np.isnan(a)
#replace the index of the missing values with the first index
idx = np.where(~mask,np.arange(mask.shape[1]),0)
print(idx)
#out = a[np.arange(idx.shape[0])[:,None], idx]
out = a[0, idx]
print(out)


[[0 0 0 3]]
[5. 5. 5. 3.]
